name: test
on:
  push:
    branches:
      - code-review
      - master

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    name: Build tap image test
    steps:
    - name: Cancel Previous Workflows In Progress
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Tap Build and Push
      id: tap-build-push
      uses: ./
      with:
        repository: simpleviewinc/tap-events-force
        cli_git_branch: master
        tap_ref: /ref/heads/tap-alias
        token: ${{ secrets.GIT_TOKEN }}
